DROP DATABASE IF EXISTS seriesDB;

CREATE DATABASE seriesDB;

USE seriesDB;

CREATE TABLE userInfo (
id INT NOT NULL AUTO_INCREMENT,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
primary key (id)
)


CREATE TABLE tvShows (
id INT NOT NULL AUTO_INCREMENT,
seriesUUID  VARCHAR(30) NOT NULL, 
userID INT NOT NULL,
FOREIGN KEY (userID) REFERENCES  userINFO(id),
PRIMARY KEY (id)
)

